a = int(input("Enter a number: "))
print(type(a))
b = input("Enter a name: ")
print(type(b))
# tup1 = input("Enter a tuple: ")
# print(type(tup1))
# l1 = eval(input("Enter a list: "))
# print(type(tup1))
# dict1 = eval(input("Enter a dictionary: "))
# print(type(dict1))
# print(type(a))
# print(type(b))
# print(type(tup1))
# print(type(l1))
# print(type(dict1))
